# -*- coding: utf-8 -*-
"""Userbased.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1c9xF7KNyD1nKW1lU923MSFI42HsGO9PW
"""

from happytransformer import HappyTextToText, TTSettings

happy_tt = HappyTextToText("T5", "vennify/t5-base-grammar-correction")

args = TTSettings(num_beams=5, min_length=1)

while True:
  inp = input("grammar: ")
  if inp == "Bye":
    print("Bot - Bye")
    break
  else:
    # Add the prefix "grammar: " before each input 
    result = happy_tt.generate_text(inp, args=args)
    print(result.text) # This sentence has bad grammar.